swagger: '2.0'
info:
  title: s3-uploader
  version: v1
tags:
  - name: main
schemes:
  - https
basePath: /
consumes:
  - octet-stream
  - application/json
produces:
  - application/json
paths:
  /save:
    post:
      consumes:
        - binary
      parameters:
        - in: body
          name: body
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
              url:
                type: string
      tags:
        - main
