swagger: '2.0'
info:
  title: s3-uploader
  version: v1
tags:
  - name: main
schemes:
  - https
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /healthcheck:
    get:
      responses:
        '200':
          description: A successful response.
      tags:
        - main
